#ifndef HTTP_HEADERS_H_
#define HTTP_HEADERS_H_

#include <string>

namespace Http
{

enum HttpHeader
{
	HEADER_AGE = 3,
	HEADER_RANGE = 5,
	HEADER_COOKIE = 6,
	HEADER_REFERER = 7,
	HEADER_DATE = 9,
	HEADER_RETRY_AFTER = 11,
	HEADER_CONTENT_TYPE = 12,
	HEADER_CONTENT_RANGE = 13,
	HEADER_TE = 14,
	HEADER_ACCEPT_LANGUAGE = 15,
	HEADER_CONTENT_LANGUAGE = 16,
	HEADER_ETAG = 17,
	HEADER_ACCEPT = 18,
	HEADER_TRAILER = 19,
	HEADER_CONNECTION = 21,
	HEADER_USER_AGENT = 22,
	HEADER_AUTHORIZATION = 24,
	HEADER_IF_RANGE = 25,
	HEADER_ACCEPT_CHARSET = 26,
	HEADER_CONTENT_LOCATION = 27,
	HEADER_ACCEPT_ENCODING = 28,
	HEADER_CONTENT_ENCODING = 29,
	HEADER_CONTENT_DISPOSITION = 30,
	HEADER_SERVER = 31,
	HEADER_EXPIRES = 32,
	HEADER_PRAGMA = 33,
	HEADER_IF_MODIFIED_SINCE = 34,
	HEADER_SET_COOKIE = 35,
	HEADER_IF_UNMODIFIED_SINCE = 36,
	HEADER_CONTENT_LENGTH = 37,
	HEADER_ACCEPT_RANGES = 38,
	HEADER_HOST = 39,
	HEADER_ALLOW = 40,
	HEADER_CACHE_CONTROL = 41,
	HEADER_TRANSFER_ENCODING = 42,
	HEADER_LINK = 43,
	HEADER_PROXY_AUTHENTICATE = 45,
	HEADER_LAST_MODIFIED = 46,
	HEADER_LOCATION = 47,
	HEADER_IF_MATCH = 48,
	HEADER_WWW_AUTHENTICATE = 51,
	HEADER_IF_NONE_MATCH = 53,
	HEADER_WARNING = 55,
	HEADER_PROXY_AUTHORIZATION = 57
};

int getHeaderId(const char* s, unsigned len) noexcept;
int getHeaderId(const std::string& s) noexcept;
const char* getHeader(int id) noexcept;

}

#endif // HTTP_HEADERS_H_
