#ifndef TRANSFER_FLAGS_H
#define TRANSFER_FLAGS_H

enum
{
	TRANSFER_FLAG_DOWNLOAD   = 0x001,
	TRANSFER_FLAG_PARTIAL    = 0x002,
	TRANSFER_FLAG_TTH_CHECK  = 0x004,
	TRANSFER_FLAG_COMPRESSED = 0x008,
	TRANSFER_FLAG_CHUNKED    = 0x010,
	TRANSFER_FLAG_SECURE     = 0x020,
	TRANSFER_FLAG_TRUSTED    = 0x040
};

#endif /* TRANSFER_FLAGS_H */
