#ifndef CONF_UI_H_
#define CONF_UI_H_

#include "../client/FeatureDef.h"

namespace Conf
{
	enum
	{
		MAGNET_ACTION_SEARCH,
		MAGNET_ACTION_DOWNLOAD,
		MAGNET_ACTION_DOWNLOAD_AND_OPEN,
		MAGNET_ACTION_OPEN_EXISTING
	};

	enum
	{
		POS_LEFT,
		POS_RIGHT
	};

	enum
	{
		TABS_TOP,
		TABS_BOTTOM
	};

	enum
	{
		WinAmp,
		WinMediaPlayer,
		iTunes,
		WinMediaPlayerClassic,
		JetAudio,
		QCDQMP,
		NumPlayers
	};

	enum
	{
		// Startup & shutdown
		// ints
		STARTUP_BACKUP = 1024,
		SHUTDOWN_ACTION,
		SHUTDOWN_TIMEOUT,
		REGISTER_URL_HANDLER,
		REGISTER_MAGNET_HANDLER,
		REGISTER_DCLST_HANDLER,
		DETECT_PREVIEW_APPS,

		// Themes and fonts
		// strings
		TEXT_FONT,
		COLOR_THEME,
		USERLIST_IMAGE,
		THEME_MANAGER_THEME_DLL_NAME,
		THEME_MANAGER_SOUNDS_THEME_NAME,
		EMOTICONS_FILE,
		ADDITIONAL_EMOTICONS,
		// ints
		COLOR_THEME_MODIFIED,

		// Colors & text styles
		// ints
		BACKGROUND_COLOR,
		TEXT_COLOR,
		ERROR_COLOR,
		TEXT_GENERAL_BACK_COLOR, TEXT_GENERAL_FORE_COLOR, TEXT_GENERAL_BOLD, TEXT_GENERAL_ITALIC,
		TEXT_MYOWN_BACK_COLOR, TEXT_MYOWN_FORE_COLOR, TEXT_MYOWN_BOLD, TEXT_MYOWN_ITALIC,
		TEXT_PRIVATE_BACK_COLOR, TEXT_PRIVATE_FORE_COLOR, TEXT_PRIVATE_BOLD, TEXT_PRIVATE_ITALIC,
		TEXT_SYSTEM_BACK_COLOR, TEXT_SYSTEM_FORE_COLOR, TEXT_SYSTEM_BOLD, TEXT_SYSTEM_ITALIC,
		TEXT_SERVER_BACK_COLOR, TEXT_SERVER_FORE_COLOR, TEXT_SERVER_BOLD, TEXT_SERVER_ITALIC,
		TEXT_TIMESTAMP_BACK_COLOR, TEXT_TIMESTAMP_FORE_COLOR, TEXT_TIMESTAMP_BOLD, TEXT_TIMESTAMP_ITALIC,
		TEXT_MYNICK_BACK_COLOR, TEXT_MYNICK_FORE_COLOR, TEXT_MYNICK_BOLD, TEXT_MYNICK_ITALIC,
		TEXT_NORMAL_BACK_COLOR, TEXT_NORMAL_FORE_COLOR, TEXT_NORMAL_BOLD, TEXT_NORMAL_ITALIC,
		TEXT_FAV_BACK_COLOR, TEXT_FAV_FORE_COLOR, TEXT_FAV_BOLD, TEXT_FAV_ITALIC,
		TEXT_OP_BACK_COLOR, TEXT_OP_FORE_COLOR, TEXT_OP_BOLD, TEXT_OP_ITALIC,
		TEXT_URL_BACK_COLOR, TEXT_URL_FORE_COLOR, TEXT_URL_BOLD, TEXT_URL_ITALIC,
		TEXT_ENEMY_BACK_COLOR, TEXT_ENEMY_FORE_COLOR, TEXT_ENEMY_BOLD, TEXT_ENEMY_ITALIC,

		// User list colors
		// ints
		RESERVED_SLOT_COLOR,
		IGNORED_COLOR,
		FAVORITE_COLOR,
		FAV_BANNED_COLOR,
		NORMAL_COLOR,
		FIREBALL_COLOR,
		SERVER_COLOR,
		PASSIVE_COLOR,
		OP_COLOR,
		CHECKED_COLOR,
		CHECKED_FAIL_COLOR,

		// Other colors
		// ints
		DOWNLOAD_BAR_COLOR,
		UPLOAD_BAR_COLOR, 
		PROGRESS_BACK_COLOR,
		PROGRESS_SEGMENT_COLOR,
		COLOR_RUNNING,
		COLOR_RUNNING_COMPLETED,
		COLOR_DOWNLOADED,
		BAN_COLOR,
		FILE_SHARED_COLOR,
		FILE_DOWNLOADED_COLOR,
		FILE_CANCELED_COLOR,
		FILE_FOUND_COLOR,
		FILE_QUEUED_COLOR,
		TABS_INACTIVE_BACKGROUND_COLOR,
		TABS_ACTIVE_BACKGROUND_COLOR,
		TABS_INACTIVE_TEXT_COLOR,
		TABS_ACTIVE_TEXT_COLOR,
		TABS_OFFLINE_BACKGROUND_COLOR,
		TABS_OFFLINE_ACTIVE_BACKGROUND_COLOR,
		TABS_UPDATED_BACKGROUND_COLOR,
		TABS_BORDER_COLOR,

		// File lists
		FILELIST_SHOW_SHARED,
		FILELIST_SHOW_DOWNLOADED,
		FILELIST_SHOW_CANCELED,
		FILELIST_SHOW_MY_UPLOADS,

		// Assorted UI settings
		// ints
		APP_DPI_AWARE,
		SHOW_GRIDLINES,
		SHOW_INFOTIPS,
		USE_SYSTEM_ICONS,
		MDI_MAXIMIZED,
		TOGGLE_ACTIVE_WINDOW,
		POPUNDER_PM,
		POPUNDER_FILELIST,

		// Tab settings
		// ints
		TABS_POS,
		MAX_TAB_ROWS,
		TAB_SIZE,
		TABS_SHOW_INFOTIPS,
		TABS_CLOSEBUTTONS,
		TABS_BOLD,
		NON_HUBS_FRONT,			
		BOLD_FINISHED_DOWNLOADS, BOLD_FINISHED_UPLOADS, BOLD_QUEUE,
		BOLD_HUB, BOLD_PM, BOLD_SEARCH, BOLD_WAITING_USERS,
		HUB_URL_IN_TITLE,

		// Toolbar settings
		// strings
		TOOLBAR,
		WINAMPTOOLBAR,
		// ints
		LOCK_TOOLBARS,
		TB_IMAGE_SIZE,
		SHOW_PLAYER_CONTROLS,

		// Menu settings
		// ints
		USE_CUSTOM_MENU,
		MENUBAR_TWO_COLORS,
		MENUBAR_LEFT_COLOR,
		MENUBAR_RIGHT_COLOR,
		MENUBAR_BUMPED,
		UC_SUBMENU,

		// Progressbar settings
		// ints
		SHOW_PROGRESS_BARS,
		PROGRESS_TEXT_COLOR_DOWN,
		PROGRESS_TEXT_COLOR_UP, 
		PROGRESS_OVERRIDE_COLORS,
		PROGRESS_3DDEPTH,
		PROGRESS_OVERRIDE_COLORS2,
		PROGRESSBAR_ODC_STYLE,
		PROGRESSBAR_ODC_BUMPED,
		STEALTHY_STYLE_ICO,
		STEALTHY_STYLE_ICO_SPEEDIGNORE,
		TOP_DL_SPEED,
		TOP_UL_SPEED,

		// Media Player message formats
		// strings
		WINAMP_FORMAT,
		WMP_FORMAT,
		ITUNES_FORMAT,
		MPLAYERC_FORMAT,
		JETAUDIO_FORMAT,
		QCDQMP_FORMAT,

		// Open at startup
		// ints
		OPEN_RECENT_HUBS,
		OPEN_PUBLIC_HUBS,
		OPEN_FAVORITE_HUBS,
		OPEN_FAVORITE_USERS,
		OPEN_QUEUE,
		OPEN_FINISHED_DOWNLOADS,
		OPEN_FINISHED_UPLOADS,
		OPEN_SEARCH_SPY,
		OPEN_NETWORK_STATISTICS,
		OPEN_NOTEPAD,
		OPEN_WAITING_USERS,
		OPEN_CDMDEBUG,
		OPEN_DHT,
		OPEN_ADLSEARCH,
		
		// Click actions
		// ints
		USERLIST_DBLCLICK,
		TRANSFERLIST_DBLCLICK,
		CHAT_DBLCLICK,
		FAVUSERLIST_DBLCLICK,
		MAGNET_ASK,
		MAGNET_ACTION,
		SHARED_MAGNET_ASK,
		SHARED_MAGNET_ACTION,
		DCLST_ASK,
		DCLST_ACTION,

		// Window behavior
		// ints
		TOPMOST,
		MINIMIZE_TRAY,
		MINIMIZE_ON_STARTUP, 
		MINIMIZE_ON_CLOSE,
		SHOW_CURRENT_SPEED_IN_TITLE,

		// Confirmations
		// ints
		CONFIRM_EXIT,
		CONFIRM_DELETE,
		CONFIRM_HUB_REMOVAL,
		CONFIRM_HUBGROUP_REMOVAL,
		CONFIRM_USER_REMOVAL,
		CONFIRM_FINISHED_REMOVAL,
		CONFIRM_SHARE_FROM_SHELL,
		CONFIRM_CLEAR_SEARCH_HISTORY,
		CONFIRM_ADLS_REMOVAL,

		// Password
		// strings
		PASSWORD,
		// ints
		PROTECT_TRAY,
		PROTECT_START,
		PROTECT_CLOSE,

		// Hub frame
		// ints
		AUTO_FOLLOW,
		SHOW_JOINS,
		FAV_SHOW_JOINS,
		PROMPT_HUB_PASSWORD,
		ENABLE_COUNTRY_FLAG,
		SHOW_CHECKED_USERS,
		HUB_POSITION,
		SORT_FAVUSERS_FIRST,
		SHOW_HIDDEN_USERS,
		FILTER_ENTER,
		JOIN_OPEN_NEW_WINDOW,
		USER_THRESHOLD,
		POPUP_PMS_HUB,
		POPUP_PMS_BOT,
		POPUP_PMS_OTHER,

		// Chat frame
		// ints
		CHAT_BUFFER_SIZE,
		CHAT_TIME_STAMPS,
		BOLD_MSG_AUTHOR,
		CHAT_PANEL_SHOW_INFOTIPS,
		SHOW_EMOTICONS_BTN,
		CHAT_ANIM_SMILES,
		SMILE_SELECT_WND_ANIM_SMILES,
		SHOW_SEND_MESSAGE_BUTTON,
#ifdef BL_UI_FEATURE_BB_CODES
		FORMAT_BB_CODES,
		FORMAT_BB_CODES_COLORS,
		SHOW_BBCODE_PANEL,
#endif
		SHOW_MULTI_CHAT_BTN,
		SHOW_TRANSCODE_BTN,
		SHOW_LINK_BTN,
		SHOW_FIND_BTN,
		CHAT_REFFERING_TO_NICK,
		STATUS_IN_CHAT,
		DISPLAY_CHEATS_IN_MAIN_CHAT,
		USE_CTRL_FOR_LINE_HISTORY,
		MULTILINE_CHAT_INPUT,
		MULTILINE_CHAT_INPUT_BY_CTRL_ENTER,
#ifdef BL_UI_FEATURE_BB_CODES
		FORMAT_BOT_MESSAGE,
#endif
		SEND_UNKNOWN_COMMANDS,
			
		// Search frame
		// ints
		SAVE_SEARCH_SETTINGS,
		FORGET_SEARCH_REQUEST,
		SEARCH_HISTORY,
		CLEAR_SEARCH,
		USE_SEARCH_GROUP_TREE_SETTINGS,
		ONLY_FREE_SLOTS,

		// Users frame
		// ints
		SHOW_IGNORED_USERS,

		// Queue frame
		// ints
		QUEUE_FRAME_SHOW_TREE,
			
		// Finished frame
		// ints
		SHOW_SHELL_MENU,

		// Search Spy frame
		// ints
		SPY_FRAME_IGNORE_TTH_SEARCHES,
		SHOW_SEEKERS_IN_SPY_FRAME,
		LOG_SEEKERS_IN_SPY_FRAME,

		// Transfers
		// ints
		TRANSFERS_ONLY_ACTIVE_UPLOADS,

		// Settings dialog
		// ints
		REMEMBER_SETTINGS_PAGE,
		SETTINGS_PAGE,
		USE_OLD_SHARING_UI,

		// Media player
		// ints
		MEDIA_PLAYER,
		USE_MAGNETS_IN_PLAYERS_SPAM,
		USE_BITRATE_FIX_FOR_SPAM,
			
		// Popup settings
		// strings
		POPUP_FONT,
		POPUP_TITLE_FONT,
		// ints
		POPUPS_DISABLED,
		POPUP_TYPE,
		POPUP_TIME,
		POPUP_WIDTH,
		POPUP_HEIGHT,
		POPUP_MAX_LENGTH,
		POPUP_BACKGROUND_COLOR,
		POPUP_TEXT_COLOR,
		POPUP_TITLE_TEXT_COLOR,
		POPUP_BORDER_COLOR,
		POPUP_ON_HUB_CONNECTED,
		POPUP_ON_HUB_DISCONNECTED,
		POPUP_ON_FAVORITE_CONNECTED,
		POPUP_ON_FAVORITE_DISCONNECTED,
		POPUP_ON_CHEATING_USER,
		POPUP_ON_CHAT_LINE,
		POPUP_ON_DOWNLOAD_STARTED,
		POPUP_ON_DOWNLOAD_FAILED,
		POPUP_ON_DOWNLOAD_FINISHED,
		POPUP_ON_UPLOAD_FINISHED,
		POPUP_ON_PM,
		POPUP_ON_NEW_PM,
		POPUP_ON_SEARCH_SPY,
		POPUP_ON_FOLDER_SHARED,
		POPUP_PM_PREVIEW,
		POPUP_ONLY_WHEN_AWAY,
		POPUP_ONLY_WHEN_MINIMIZED, 

		// Sounds
		// strings
		SOUND_BEEPFILE,
		SOUND_BEGINFILE,
		SOUND_FINISHFILE,
		SOUND_SOURCEFILE,
		SOUND_UPLOADFILE,
		SOUND_FAKERFILE,
		SOUND_CHATNAMEFILE,
		SOUND_TTH,
		SOUND_HUBCON,
		SOUND_HUBDISCON,
		SOUND_FAVUSER,
		SOUND_FAVUSER_OFFLINE,
		SOUND_TYPING_NOTIFY,
		SOUND_SEARCHSPY,
		// ints
		SOUNDS_DISABLED,
		PRIVATE_MESSAGE_BEEP,
		PRIVATE_MESSAGE_BEEP_OPEN,

		// Frames UI state
		// strings
		TRANSFER_FRAME_ORDER, TRANSFER_FRAME_WIDTHS, TRANSFER_FRAME_VISIBLE,
		SEARCH_FRAME_ORDER, SEARCH_FRAME_WIDTHS, SEARCH_FRAME_VISIBLE,
		DIRLIST_FRAME_ORDER, DIRLIST_FRAME_WIDTHS, DIRLIST_FRAME_VISIBLE,
		FAVORITES_FRAME_ORDER, FAVORITES_FRAME_WIDTHS, FAVORITES_FRAME_VISIBLE,
		QUEUE_FRAME_ORDER, QUEUE_FRAME_WIDTHS, QUEUE_FRAME_VISIBLE,
		PUBLIC_HUBS_FRAME_ORDER, PUBLIC_HUBS_FRAME_WIDTHS, PUBLIC_HUBS_FRAME_VISIBLE,
		USERS_FRAME_ORDER, USERS_FRAME_WIDTHS, USERS_FRAME_VISIBLE,
		FINISHED_DL_FRAME_ORDER, FINISHED_DL_FRAME_WIDTHS, FINISHED_DL_FRAME_VISIBLE,
		FINISHED_UL_FRAME_WIDTHS, FINISHED_UL_FRAME_ORDER, FINISHED_UL_FRAME_VISIBLE,
		UPLOAD_QUEUE_FRAME_ORDER, UPLOAD_QUEUE_FRAME_WIDTHS, UPLOAD_QUEUE_FRAME_VISIBLE,
		RECENTS_FRAME_ORDER, RECENTS_FRAME_WIDTHS, RECENTS_FRAME_VISIBLE, 
		ADLSEARCH_FRAME_ORDER, ADLSEARCH_FRAME_WIDTHS, ADLSEARCH_FRAME_VISIBLE,
		SPY_FRAME_WIDTHS, SPY_FRAME_ORDER, SPY_FRAME_VISIBLE,
		// ints
		TRANSFER_FRAME_SORT, TRANSFER_FRAME_SPLIT,
		HUB_FRAME_SORT,
		SEARCH_FRAME_SORT,
		DIRLIST_FRAME_SORT, DIRLIST_FRAME_SPLIT,
		FAVORITES_FRAME_SORT,
		QUEUE_FRAME_SORT, QUEUE_FRAME_SPLIT,
		PUBLIC_HUBS_FRAME_SORT,
		USERS_FRAME_SORT, USERS_FRAME_SPLIT,
		FINISHED_DL_FRAME_SORT,
		FINISHED_UL_FRAME_SORT,
		UPLOAD_QUEUE_FRAME_SORT, UPLOAD_QUEUE_FRAME_SPLIT,
		RECENTS_FRAME_SORT,
		ADLSEARCH_FRAME_SORT,
		SPY_FRAME_SORT,

		// View visibility
		// ints
		SHOW_STATUSBAR,
		SHOW_TOOLBAR,
		SHOW_TRANSFERVIEW,
		SHOW_QUICK_SEARCH,

		// Main window size & position
		// ints
		MAIN_WINDOW_STATE,
		MAIN_WINDOW_SIZE_X,
		MAIN_WINDOW_SIZE_Y,
		MAIN_WINDOW_POS_X,
		MAIN_WINDOW_POS_Y,

		// Other settings, mostly useless
		// ints
		AUTO_AWAY,
		REDUCE_PRIORITY_IF_MINIMIZED_TO_TRAY,
		DCLST_CREATE_IN_SAME_FOLDER,
		DCLST_INCLUDESELF,
		SEARCH_MAGNET_SOURCES,
		// strings
		DCLST_DIRECTORY,

		// Recents
		// strings
		SAVED_SEARCH_SIZE,
		KICK_MSG_RECENT_01, KICK_MSG_RECENT_02, KICK_MSG_RECENT_03, KICK_MSG_RECENT_04, KICK_MSG_RECENT_05,
		KICK_MSG_RECENT_06, KICK_MSG_RECENT_07, KICK_MSG_RECENT_08, KICK_MSG_RECENT_09, KICK_MSG_RECENT_10,
		KICK_MSG_RECENT_11, KICK_MSG_RECENT_12, KICK_MSG_RECENT_13, KICK_MSG_RECENT_14, KICK_MSG_RECENT_15,
		KICK_MSG_RECENT_16, KICK_MSG_RECENT_17, KICK_MSG_RECENT_18, KICK_MSG_RECENT_19, KICK_MSG_RECENT_20,
		// ints
		SAVED_SEARCH_TYPE,
		SAVED_SEARCH_SIZEMODE,
		SAVED_SEARCH_MODE
	};

	void initUiSettings();
	void updateUiSettingsDefaults();
	void processUiSettings();
}

#endif // CONF_UI_H_
