#define SQLITE_DEFAULT_CACHE_SIZE 8000

#define SQLITE_DQS 0
#define SQLITE_DEFAULT_MEMSTATUS 0
#define SQLITE_LIKE_DOESNT_MATCH_BLOBS

#define SQLITE_OMIT_DEPRECATED
#define SQLITE_OMIT_DECLTYPE
#define SQLITE_OMIT_AUTOINIT
#define SQLITE_OMIT_TRIGGER
#define SQLITE_OMIT_UTF16

#define SQLITE_USE_ALLOCA

#if defined _POSIX_SOURCE || defined _GNU_SOURCE
#define HAVE_LOCALTIME_R
#define HAVE_GMTIME_R
#endif
